### ISSUE TITLE
11. Extra Bonus - Authentication or Rate limiting (Alex asked in discord)

### ISSUE THREAD

**Issue by alexmazaltov** [LuisJoseSanchez/encode-club-ai-and-gpt-bootcamp-q3-homework-week2#6]
from Discord:
> I want we talk also about [Lesson-6/Ex4](https://github.com/Encode-Club-AI-Bootcamp/Generative-AI-Applications/blob/main/Lesson-06/exercises/04-Add-Features-AI-Chat-Template.md) important for me to have limitation to avoid token spending on live

@alexmazaltov if you have any information or suggestion post here and I'll have a look.
Do we have some examples in the encode repo already?

@ionescu77 Check the limit implementation in [my branch](https://github.com/LuisJoseSanchez/encode-club-ai-and-gpt-bootcamp-q3-homework-week2/commit/e5d9fa2aecc20b4af368b6d8217b023f823057dd)

**Comment by ionescu77** [comment]
## Front-end only encrypt with javascript

This is so dope, just discovered it in my github feed

https://github.com/robinmoisson/staticrypt

**Comment by alexmazaltov** [comment]
I see. It could be good approach to use: 

```
StatiCrypt generates a static, password protected page that can be decrypted in-browser: just send or upload the generated page to a place serving static content (github pages, for example) and you're done: the javascript will prompt users for password, decrypt the page and load your HTML.
```

**Comment by ionescu77** [comment]
Alex added rate limiter in commit 45f496a using `rate-limiter-flexible` package
